const PACKAGE_STATUSES = {
  RECIBIDO_MIAMI: 'recibido_miami',
  ALMACEN_MIAMI: 'almacen_miami',
  EN_TRANSITO: 'en_transito',
  LLEGO_RD: 'llego_rd',
  ALMACEN_RD: 'almacen_rd',
  DISPONIBLE: 'disponible',
  EN_REPARTO: 'en_reparto',
  ENTREGADO: 'entregado',
  CANCELADO: 'cancelado',
  EXTRAVIADO: 'extraviado',
};

const PACKAGE_STATUS_LIST = Object.values(PACKAGE_STATUSES);

const STATUS_TRANSITIONS = {
  [PACKAGE_STATUSES.RECIBIDO_MIAMI]: [PACKAGE_STATUSES.ALMACEN_MIAMI],
  [PACKAGE_STATUSES.ALMACEN_MIAMI]: [PACKAGE_STATUSES.EN_TRANSITO],
  [PACKAGE_STATUSES.EN_TRANSITO]: [PACKAGE_STATUSES.LLEGO_RD],
  [PACKAGE_STATUSES.LLEGO_RD]: [PACKAGE_STATUSES.ALMACEN_RD],
  [PACKAGE_STATUSES.ALMACEN_RD]: [PACKAGE_STATUSES.DISPONIBLE, PACKAGE_STATUSES.CANCELADO, PACKAGE_STATUSES.EXTRAVIADO],
  [PACKAGE_STATUSES.DISPONIBLE]: [PACKAGE_STATUSES.EN_REPARTO, PACKAGE_STATUSES.ENTREGADO, PACKAGE_STATUSES.CANCELADO],
  [PACKAGE_STATUSES.EN_REPARTO]: [PACKAGE_STATUSES.ENTREGADO, PACKAGE_STATUSES.DISPONIBLE],
  [PACKAGE_STATUSES.ENTREGADO]: [],
  [PACKAGE_STATUSES.CANCELADO]: [],
  [PACKAGE_STATUSES.EXTRAVIADO]: [],
};

module.exports = { PACKAGE_STATUSES, PACKAGE_STATUS_LIST, STATUS_TRANSITIONS };